/*
 * MIT License
 *
 * Copyright (c) 2017 Ingenia-CAT S.L.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include "public/ingenialink/registers.h"

/*******************************************************************************
 * Public
 ******************************************************************************/

const il_reg_t IL_REG_PAIR_POLES = {
	0x2301, 0x00, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_FB_VEL_SENSOR = {
	0x2310, 0x01, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_FB_POS_SENSOR = {
	0x2310, 0x03, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_SSI_STURNBITS = {
	0x2380, 0x05, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_MOTPARAM_PPITCH = {
	0x2701, 0x03, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_MONITOR_CFG_T_S = {
	0x2c50, 0x01, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_MONITOR_CFG_ENABLE = {
	0x2c50, 0x02, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_MONITOR_CFG_DELAY_SAMPLES = {
	0x2c50, 0x03, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_MONITOR_RESULT_SZ = {
	0x2c51, 0x01, IL_REG_DTYPE_U16, IL_REG_ACCESS_RO, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_MONITOR_RESULT_FILLED = {
	0x2c51, 0x02, IL_REG_DTYPE_U16, IL_REG_ACCESS_RO, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_MONITOR_RESULT_ENTRY = {
	0x2c51, 0x03, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_MONITOR_RESULT_CH_1 = {
	0x2c51, 0x04, IL_REG_DTYPE_S32, IL_REG_ACCESS_RO, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_MONITOR_RESULT_CH_2 = {
	0x2c51, 0x05, IL_REG_DTYPE_S32, IL_REG_ACCESS_RO, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_MONITOR_RESULT_CH_3 = {
	0x2c51, 0x06, IL_REG_DTYPE_S32, IL_REG_ACCESS_RO, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_MONITOR_RESULT_CH_4 = {
	0x2c51, 0x07, IL_REG_DTYPE_S32, IL_REG_ACCESS_RO, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_MONITOR_MAP_CH_1 = {
	0x2c52, 0x01, IL_REG_DTYPE_S32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_MONITOR_MAP_CH_2 = {
	0x2c52, 0x02, IL_REG_DTYPE_S32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_MONITOR_MAP_CH_3 = {
	0x2c52, 0x03, IL_REG_DTYPE_S32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_MONITOR_MAP_CH_4 = {
	0x2c52, 0x04, IL_REG_DTYPE_S32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_MONITOR_TRIG_MODE = {
	0x2c55, 0x01, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_MONITOR_TRIG_SRC = {
	0x2c55, 0x02, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_MONITOR_TRIG_TH_POS = {
	0x2c55, 0x03, IL_REG_DTYPE_S32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_MONITOR_TRIG_TH_NEG = {
	0x2c55, 0x04, IL_REG_DTYPE_S32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_MONITOR_TRIG_DIN_MSK = {
	0x2c55, 0x05, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_MONITOR_TRIG_DELAY = {
	0x2c55, 0x06, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_OL_VOLTAGE = {
	0x2d00, 0x01, IL_REG_DTYPE_S16, IL_REG_ACCESS_RW, IL_REG_PHY_VOLT_REL
};

const il_reg_t IL_REG_OL_FREQUENCY = {
	0x2d00, 0x02, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_SENSING_RES = {
	0x2ff0, 0x01, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_PREAMP_G = {
	0x2ff0, 0x02, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_HAS_VGA = {
	0x2ff0, 0x03, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_HAS_T_SENSOR = {
	0x2ff0, 0x04, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_T_MAX = {
	0x2ff0, 0x05, IL_REG_DTYPE_S32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_T_MIN = {
	0x2ff0, 0x06, IL_REG_DTYPE_S32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_HAS_VBUS_SENSOR = {
	0x2ff0, 0x07, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_V_MAX = {
	0x2ff0, 0x08, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_V_MIN = {
	0x2ff0, 0x09, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_CURR_NOM = {
	0x2ff0, 0x0A, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_CURR_PEAK = {
	0x2ff0, 0x0B, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_PEAK_TIME_MAX = {
	0x2ff0, 0x0C, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_CURR_PEAK_MAX = {
	0x2ff0, 0x0D, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_HAS_STEPPER_3PH = {
	0x2ff0, 0x0E, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_HAS_NVM = {
	0x2ff0, 0x0F, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_HAS_HW_ERR = {
	0x2ff0, 0x10, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_T_SENSOR_OFFSET = {
	0x2ff0, 0x11, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_T_SENSOR_GAIN = {
	0x2ff0, 0x12, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_VBUS_SENSOR_GAIN = {
	0x2ff0, 0x13, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_DEADTIME = {
	0x2ff0, 0x14, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_PWM_FREQ_LEGACY = {
	0x2ff0, 0x15, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_BOOTSTRAP_CHRG_TIME = {
	0x2ff0, 0x16, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_HAS_NTC = {
	0x2ff0, 0x17, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_NTC_REXT = {
	0x2ff0, 0x18, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_NTC_R25 = {
	0x2ff0, 0x19, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_NTC_B25 = {
	0x2ff0, 0x1A, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_HAS_RESOLVER = {
	0x2ff0, 0x1B, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_HW_NODEID = {
	0x2ff0, 0x1C, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_PWM_FREQ = {
	0x2ff0, 0x1D, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_DIN_AVAIL = {
	0x2ff0, 0x1E, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_DOUT_AVAIL = {
	0x2ff0, 0x1F, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_AIN_AVAIL = {
	0x2ff0, 0x20, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_AOUT_AVAIL = {
	0x2ff0, 0x21, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_PROD_ID = {
	0x2ff0, 0x22, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_SERIAL = {
	0x2ff0, 0x23, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_2PH_SW_SCHEME = {
	0x2ff0, 0x24, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_ENA_IN_UART = {
	0x2ff0, 0x25, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_CURR_SENSORS_AVAIL = {
	0x2ff0, 0x26, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_DIN_POL_MSK = {
	0x2ff0, 0x27, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_DOUT_POL_MSK = {
	0x2ff0, 0x28, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_AREF = {
	0x2ff0, 0x29, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_AIN12_PARAM = {
	0x2ff0, 0x2A, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_AIN34_PARAM = {
	0x2ff0, 0x2B, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_AOUT12_PARAM = {
	0x2ff0, 0x2C, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_MACRO_PARAM = {
	0x2ff0, 0x2D, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_MOTOR_SUP = {
	0x2ff0, 0x2E, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_COMMS_SUP = {
	0x2ff0, 0x2F, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_FEEDBACKS_SUP = {
	0x2ff0, 0x30, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_PWM_DUTY_MAX = {
	0x2ff0, 0x31, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_CURR_LOOP_FREQ = {
	0x2ff0, 0x32, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_VELPOS_LOOP_FREQ = {
	0x2ff0, 0x33, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_CMDSRC_SUP = {
	0x2ff0, 0x34, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_STO_IN = {
	0x2ff0, 0x35, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_PWM_FREQ_ALT = {
	0x2ff0, 0x36, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_CURR_LPF_OUT = {
	0x2ff0, 0x37, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_AIN5_PARAM = {
	0x2ff0, 0x38, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_OLP_IN = {
	0x2ff0, 0x39, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_SHUNT_OUT = {
	0x2ff0, 0x3A, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_BRAKE_OUT = {
	0x2ff0, 0x3B, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_KEY = {
	0x2ff1, 0x00, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_REG_CNT = {
	0x2ff3, 0x00, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HW_VERSION = {
	0x2ff4, 0x01, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HW_VARIANT = {
	0x2ff4, 0x02, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_PROG_DATE = {
	0x2ff4, 0x03, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_HWC_REVISION = {
	0x2ff4, 0x04, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

/* CiA 402 */
const il_reg_t IL_REG_CTL_WORD = {
	0x6040, 0x00, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_STS_WORD = {
	0x6041, 0x00, IL_REG_DTYPE_U16, IL_REG_ACCESS_RO, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_OP_MODE = {
	0x6060, 0x00, IL_REG_DTYPE_S8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_POS_ACT = {
	0x6064, 0x00, IL_REG_DTYPE_S32, IL_REG_ACCESS_RW, IL_REG_PHY_POS
};

const il_reg_t IL_REG_VEL_ACT = {
	0x606C, 0x00, IL_REG_DTYPE_S32, IL_REG_ACCESS_RW, IL_REG_PHY_VEL
};

const il_reg_t IL_REG_TORQUE_TGT = {
	0x6071, 0x00, IL_REG_DTYPE_S16, IL_REG_ACCESS_RW, IL_REG_PHY_TORQUE
};

const il_reg_t IL_REG_RATED_TORQUE = {
	0x6076, 0x00, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_TORQUE_ACT = {
	0x6077, 0x00, IL_REG_DTYPE_S16, IL_REG_ACCESS_RW, IL_REG_PHY_TORQUE
};

const il_reg_t IL_REG_POS_TGT = {
	0x607A, 0x00, IL_REG_DTYPE_S32, IL_REG_ACCESS_RW, IL_REG_PHY_POS
};

const il_reg_t IL_REG_PRES_ENC_INCR = {
	0x608F, 0x01, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_PRES_MOTOR_REVS = {
	0x608F, 0x02, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_VRES_ENC_INCR = {
	0x6090, 0x01, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_VRES_MOTOR_REVS = {
	0x6090, 0x02, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

const il_reg_t IL_REG_VEL_TGT = {
	0x60FF, 0x00, IL_REG_DTYPE_S32, IL_REG_ACCESS_RW, IL_REG_PHY_VEL
};
