/*
 * MIT License
 *
 * Copyright (c) 2017 Ingenia-CAT S.L.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include "public/ingenialink/registers.h"

/*******************************************************************************
 * Public
 ******************************************************************************/

/*
 * CiA 301.
 */

IL_EXPORT const il_reg_t IL_REG_SW_VERSION = {
	0x00100A, IL_REG_DTYPE_U64, IL_REG_ACCESS_RO, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_STORE_ALL = {
	0x011010, IL_REG_DTYPE_U32, IL_REG_ACCESS_WO, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_STORE_COMM = {
	0x021010, IL_REG_DTYPE_U32, IL_REG_ACCESS_WO, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_STORE_APP = {
	0x031010, IL_REG_DTYPE_U32, IL_REG_ACCESS_WO, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_ID_VID = {
	0x011018, IL_REG_DTYPE_U32, IL_REG_ACCESS_RO, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_ID_PROD_CODE = {
	0x021018, IL_REG_DTYPE_U32, IL_REG_ACCESS_RO, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_ID_REVISION = {
	0x031018, IL_REG_DTYPE_U32, IL_REG_ACCESS_RO, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_ID_SERIAL = {
	0x041018, IL_REG_DTYPE_U32, IL_REG_ACCESS_RO, IL_REG_PHY_NONE
};

/*
 * Vendor specific (Ingenia).
 */

IL_EXPORT const il_reg_t IL_REG_PAIR_POLES = {
	0x002301, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_COMMUTATION_SENSOR = {
	0x012305, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_COMMUTATION_IANGLE_METHOD = {
	0x022305, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_COMMUTATION_ANGLE_ACT = {
	0x032305, IL_REG_DTYPE_U16, IL_REG_ACCESS_RO, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_COMMUTATION_REF_SENSOR = {
	0x042305, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_COMMUTATION_ANGLE_OFF = {
	0x052305, IL_REG_DTYPE_U16, IL_REG_ACCESS_RO, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_NINCR_ALIGN_OFFSET_PHASE_A = {
	0x012308, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_RAD
};

IL_EXPORT const il_reg_t IL_REG_FB_TORQUE_SENSOR = {
	0x012310, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_FB_VEL_SENSOR = {
	0x022310, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_FB_POS_SENSOR = {
	0x032310, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_DENC_SINCOS_SWAP = {
	0x002311, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_DENC_SINCOS_TYPE = {
	0x002312, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_DENC_SINCOS_FILTER = {
	0x002313, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_SSI_STURNBITS = {
	0x052380, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_CMD_SRC = {
	0x002430, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_TORQUE_DEM_LPF_ENABLED = {
	0x012504, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_TORQUE_DEM_LPF_CFREQ = {
	0x022504, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_CL_TORQUE_BYPASS = {
	0x012507, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_CL_FB_POS_OPEN = {
	0x022507, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_CL_FB_VEL_OPEN = {
	0x032507, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_CL_FB_TORQUE_OPEN = {
	0x042507, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_CL_VEL_USE_POS = {
	0x052507, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_TORQUE_WINDOW = {
	0x002508, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_TORQUE
};

IL_EXPORT const il_reg_t IL_REG_TORQUE_WINDOW_TIME = {
	0x002509, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_DSIG_MAX_ENTRIES = {
	0x01250a, IL_REG_DTYPE_U16, IL_REG_ACCESS_RO, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_DSIG_FILLED_ENTRIES = {
	0x02250a, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_DSIG_ENTRY_NUM = {
	0x03250a, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_DSIG_ENTRY_VAL = {
	0x04250a, IL_REG_DTYPE_S32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_DSIG_INJ_POINT = {
	0x05250a, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_DSIG_NCYCLES = {
	0x06250a, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_DSIG_RATE = {
	0x07250a, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_DSIG_OUT = {
	0x08250a, IL_REG_DTYPE_S32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_MOTPARAM_RES_PHTOPH = {
	0x012701, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_MOTPARAM_IND_PHTOPH = {
	0x022701, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_MOTPARAM_PPITCH = {
	0x032701, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_MOTPARAM_KV = {
	0x042701, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_MOTPARAM_STROKE = {
	0x052701, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_MOTPARAM_KM = {
	0x062701, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_MONITOR_CFG_T_S = {
	0x012c50, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_MONITOR_CFG_ENABLE = {
	0x022c50, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_MONITOR_CFG_DELAY_SAMPLES = {
	0x032c50, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_MONITOR_RESULT_SZ = {
	0x012c51, IL_REG_DTYPE_U16, IL_REG_ACCESS_RO, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_MONITOR_RESULT_FILLED = {
	0x022c51, IL_REG_DTYPE_U16, IL_REG_ACCESS_RO, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_MONITOR_RESULT_ENTRY = {
	0x032c51, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_MONITOR_RESULT_CH_1 = {
	0x042c51, IL_REG_DTYPE_S32, IL_REG_ACCESS_RO, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_MONITOR_RESULT_CH_2 = {
	0x052c51, IL_REG_DTYPE_S32, IL_REG_ACCESS_RO, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_MONITOR_RESULT_CH_3 = {
	0x062c51, IL_REG_DTYPE_S32, IL_REG_ACCESS_RO, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_MONITOR_RESULT_CH_4 = {
	0x072c51, IL_REG_DTYPE_S32, IL_REG_ACCESS_RO, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_MONITOR_MAP_CH_1 = {
	0x012c52, IL_REG_DTYPE_S32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_MONITOR_MAP_CH_2 = {
	0x022c52, IL_REG_DTYPE_S32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_MONITOR_MAP_CH_3 = {
	0x032c52, IL_REG_DTYPE_S32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_MONITOR_MAP_CH_4 = {
	0x042c52, IL_REG_DTYPE_S32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_MONITOR_TRIG_MODE = {
	0x012c55, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_MONITOR_TRIG_SRC = {
	0x022c55, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_MONITOR_TRIG_TH_POS = {
	0x032c55, IL_REG_DTYPE_S32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_MONITOR_TRIG_TH_NEG = {
	0x042c55, IL_REG_DTYPE_S32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_MONITOR_TRIG_DIN_MSK = {
	0x052c55, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_MONITOR_TRIG_DELAY = {
	0x062c55, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_OL_VOLTAGE = {
	0x012d00, IL_REG_DTYPE_S16, IL_REG_ACCESS_RW, IL_REG_PHY_VOLT_REL
};

IL_EXPORT const il_reg_t IL_REG_OL_FREQUENCY = {
	0x022d00, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_SENSING_RES = {
	0x012ff0, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_PREAMP_G = {
	0x022ff0, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_HAS_VGA = {
	0x032ff0, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_HAS_T_SENSOR = {
	0x042ff0, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_T_MAX = {
	0x052ff0, IL_REG_DTYPE_S32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_T_MIN = {
	0x062ff0, IL_REG_DTYPE_S32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_HAS_VBUS_SENSOR = {
	0x072ff0, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_V_MAX = {
	0x082ff0, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_V_MIN = {
	0x092ff0, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_CURR_NOM = {
	0x0A2ff0, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_CURR_PEAK = {
	0x0B2ff0, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_PEAK_TIME_MAX = {
	0x0C2ff0, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_CURR_PEAK_MAX = {
	0x0D2ff0, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_HAS_STEPPER_3PH = {
	0x0E2ff0, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_HAS_NVM = {
	0x0F2ff0, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_HAS_HW_ERR = {
	0x102ff0, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_T_SENSOR_OFFSET = {
	0x112ff0, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_T_SENSOR_GAIN = {
	0x122ff0, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_VBUS_SENSOR_GAIN = {
	0x132ff0, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_DEADTIME = {
	0x142ff0, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_PWM_FREQ_LEGACY = {
	0x152ff0, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_BOOTSTRAP_CHRG_TIME = {
	0x162ff0, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_HAS_NTC = {
	0x172ff0, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_NTC_REXT = {
	0x182ff0, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_NTC_R25 = {
	0x192ff0, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_NTC_B25 = {
	0x1A2ff0, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_HAS_RESOLVER = {
	0x1B2ff0, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_HW_NODEID = {
	0x1C2ff0, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_PWM_FREQ = {
	0x1D2ff0, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_DIN_AVAIL = {
	0x1E2ff0, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_DOUT_AVAIL = {
	0x1F2ff0, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_AIN_AVAIL = {
	0x202ff0, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_AOUT_AVAIL = {
	0x212ff0, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_PROD_ID = {
	0x222ff0, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_SERIAL = {
	0x232ff0, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_2PH_SW_SCHEME = {
	0x242ff0, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_ENA_IN_UART = {
	0x252ff0, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_CURR_SENSORS_AVAIL = {
	0x262ff0, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_DIN_POL_MSK = {
	0x272ff0, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_DOUT_POL_MSK = {
	0x282ff0, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_AREF = {
	0x292ff0, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_AIN12_PARAM = {
	0x2A2ff0, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_AIN34_PARAM = {
	0x2B2ff0, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_AOUT12_PARAM = {
	0x2C2ff0, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_MACRO_PARAM = {
	0x2D2ff0, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_MOTOR_SUP = {
	0x2E2ff0, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_COMMS_SUP = {
	0x2F2ff0, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_FEEDBACKS_SUP = {
	0x302ff0, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_PWM_DUTY_MAX = {
	0x312ff0, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_CURR_LOOP_FREQ = {
	0x322ff0, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_VELPOS_LOOP_FREQ = {
	0x332ff0, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_CMDSRC_SUP = {
	0x342ff0, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_STO_IN = {
	0x352ff0, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_PWM_FREQ_ALT = {
	0x362ff0, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_CURR_LPF_OUT = {
	0x372ff0, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_AIN5_PARAM = {
	0x382ff0, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_OLP_IN = {
	0x392ff0, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_SHUNT_OUT = {
	0x3A2ff0, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_BRAKE_OUT = {
	0x3B2ff0, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_KEY = {
	0x002ff1, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_REG_CNT = {
	0x002ff3, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HW_VERSION = {
	0x012ff4, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HW_VARIANT = {
	0x022ff4, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_PROG_DATE = {
	0x032ff4, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_HWC_REVISION = {
	0x042ff4, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_DRIVE_NAME = {
	0x002ffe, IL_REG_DTYPE_U64, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_RESET = {
	0x002fff, IL_REG_DTYPE_U32, IL_REG_ACCESS_WO, IL_REG_PHY_NONE
};

/* CiA 402 */
IL_EXPORT const il_reg_t IL_REG_CTL_WORD = {
	0x006040, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_STS_WORD = {
	0x006041, IL_REG_DTYPE_U16, IL_REG_ACCESS_RO, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_OP_MODE = {
	0x006060, IL_REG_DTYPE_S8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_OP_MODE_DISP = {
	0x006061, IL_REG_DTYPE_S8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_POS_ACT = {
	0x006064, IL_REG_DTYPE_S32, IL_REG_ACCESS_RW, IL_REG_PHY_POS
};

IL_EXPORT const il_reg_t IL_REG_VEL_ACT = {
	0x00606C, IL_REG_DTYPE_S32, IL_REG_ACCESS_RW, IL_REG_PHY_VEL
};

IL_EXPORT const il_reg_t IL_REG_TORQUE_TGT = {
	0x006071, IL_REG_DTYPE_S16, IL_REG_ACCESS_RW, IL_REG_PHY_TORQUE
};

IL_EXPORT const il_reg_t IL_REG_TORQUE_MAX = {
	0x006072, IL_REG_DTYPE_S16, IL_REG_ACCESS_RW, IL_REG_PHY_TORQUE
};

IL_EXPORT const il_reg_t IL_REG_RATED_CURRENT = {
	0x006075, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_RATED_TORQUE = {
	0x006076, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_TORQUE_ACT = {
	0x006077, IL_REG_DTYPE_S16, IL_REG_ACCESS_RW, IL_REG_PHY_TORQUE
};

IL_EXPORT const il_reg_t IL_REG_DC_VOLTAGE = {
	0x006079, IL_REG_DTYPE_U32, IL_REG_ACCESS_RO, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_POS_TGT = {
	0x00607A, IL_REG_DTYPE_S32, IL_REG_ACCESS_RW, IL_REG_PHY_POS
};

IL_EXPORT const il_reg_t IL_REG_TORQUE_SLOPE = {
	0x006087, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_TORQUE
};

IL_EXPORT const il_reg_t IL_REG_PRES_ENC_INCR = {
	0x01608F, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_PRES_MOTOR_REVS = {
	0x02608F, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_VRES_ENC_INCR = {
	0x016090, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_VRES_MOTOR_REVS = {
	0x026090, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

IL_EXPORT const il_reg_t IL_REG_VEL_TGT = {
	0x0060FF, IL_REG_DTYPE_S32, IL_REG_ACCESS_RW, IL_REG_PHY_VEL
};

IL_EXPORT const il_reg_t IL_REG_MOTOR_TYPE = {
	0x006402, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE
};

