/*
 * MIT License
 *
 * Copyright (c) 2017 Ingenia-CAT S.L.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include "public/ingenialink/registers.h"

/*******************************************************************************
 * Public
 ******************************************************************************/

/*
 * CiA 301.
 */

const il_reg_t IL_REG_SW_VERSION = {
	0x00100A, IL_REG_DTYPE_U64, IL_REG_ACCESS_RO, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_STORE_ALL = {
	0x011010, IL_REG_DTYPE_U32, IL_REG_ACCESS_WO, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_STORE_COMM = {
	0x021010, IL_REG_DTYPE_U32, IL_REG_ACCESS_WO, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_STORE_APP = {
	0x031010, IL_REG_DTYPE_U32, IL_REG_ACCESS_WO, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_ID_PROD_CODE = {
	0x021018, IL_REG_DTYPE_U32, IL_REG_ACCESS_RO, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_ID_REVISION = {
	0x031018, IL_REG_DTYPE_U32, IL_REG_ACCESS_RO, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_ID_SERIAL = {
	0x041018, IL_REG_DTYPE_U32, IL_REG_ACCESS_RO, IL_REG_PHY_NONE, NULL
};

/*
 * Vendor specific (Ingenia).
 */

const il_reg_t IL_REG_PAIR_POLES = {
	0x002301, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_FB_VEL_SENSOR = {
	0x022310, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_FB_POS_SENSOR = {
	0x032310, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_SSI_STURNBITS = {
	0x052380, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_MOTPARAM_PPITCH = {
	0x032701, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_MONITOR_CFG_T_S = {
	0x012c50, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_MONITOR_CFG_ENABLE = {
	0x022c50, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_MONITOR_CFG_DELAY_SAMPLES = {
	0x032c50, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_MONITOR_RESULT_SZ = {
	0x012c51, IL_REG_DTYPE_U16, IL_REG_ACCESS_RO, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_MONITOR_RESULT_FILLED = {
	0x022c51, IL_REG_DTYPE_U16, IL_REG_ACCESS_RO, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_MONITOR_RESULT_ENTRY = {
	0x032c51, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_MONITOR_RESULT_CH_1 = {
	0x042c51, IL_REG_DTYPE_S32, IL_REG_ACCESS_RO, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_MONITOR_RESULT_CH_2 = {
	0x052c51, IL_REG_DTYPE_S32, IL_REG_ACCESS_RO, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_MONITOR_RESULT_CH_3 = {
	0x062c51, IL_REG_DTYPE_S32, IL_REG_ACCESS_RO, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_MONITOR_RESULT_CH_4 = {
	0x072c51, IL_REG_DTYPE_S32, IL_REG_ACCESS_RO, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_MONITOR_MAP_CH_1 = {
	0x012c52, IL_REG_DTYPE_S32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_MONITOR_MAP_CH_2 = {
	0x022c52, IL_REG_DTYPE_S32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_MONITOR_MAP_CH_3 = {
	0x032c52, IL_REG_DTYPE_S32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_MONITOR_MAP_CH_4 = {
	0x042c52, IL_REG_DTYPE_S32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_MONITOR_TRIG_MODE = {
	0x012c55, IL_REG_DTYPE_U8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_MONITOR_TRIG_SRC = {
	0x022c55, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_MONITOR_TRIG_TH_POS = {
	0x032c55, IL_REG_DTYPE_S32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_MONITOR_TRIG_TH_NEG = {
	0x042c55, IL_REG_DTYPE_S32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_MONITOR_TRIG_DIN_MSK = {
	0x052c55, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_MONITOR_TRIG_DELAY = {
	0x062c55, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_OL_VOLTAGE = {
	0x012d00, IL_REG_DTYPE_S16, IL_REG_ACCESS_RW, IL_REG_PHY_VOLT_REL, NULL
};

const il_reg_t IL_REG_OL_FREQUENCY = {
	0x022d00, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_HW_VARIANT = {
	0x022ff4, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_DRIVE_NAME = {
	0x002ffe, IL_REG_DTYPE_U64, IL_REG_ACCESS_RW, IL_REG_PHY_NONE, NULL
};

/* CiA 402 */
const il_reg_t IL_REG_CTL_WORD = {
	0x006040, IL_REG_DTYPE_U16, IL_REG_ACCESS_RW, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_STS_WORD = {
	0x006041, IL_REG_DTYPE_U16, IL_REG_ACCESS_RO, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_OP_MODE = {
	0x006060, IL_REG_DTYPE_S8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_OP_MODE_DISP = {
	0x006061, IL_REG_DTYPE_S8, IL_REG_ACCESS_RW, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_POS_ACT = {
	0x006064, IL_REG_DTYPE_S32, IL_REG_ACCESS_RW, IL_REG_PHY_POS, NULL
};

const il_reg_t IL_REG_VEL_ACT = {
	0x00606C, IL_REG_DTYPE_S32, IL_REG_ACCESS_RW, IL_REG_PHY_VEL, NULL
};

const il_reg_t IL_REG_TORQUE_TGT = {
	0x006071, IL_REG_DTYPE_S16, IL_REG_ACCESS_RW, IL_REG_PHY_TORQUE, NULL
};

const il_reg_t IL_REG_RATED_TORQUE = {
	0x006076, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_TORQUE_ACT = {
	0x006077, IL_REG_DTYPE_S16, IL_REG_ACCESS_RW, IL_REG_PHY_TORQUE, NULL
};

const il_reg_t IL_REG_POS_TGT = {
	0x00607A, IL_REG_DTYPE_S32, IL_REG_ACCESS_RW, IL_REG_PHY_POS, NULL
};

const il_reg_t IL_REG_PRES_ENC_INCR = {
	0x01608F, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_PRES_MOTOR_REVS = {
	0x02608F, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_VRES_ENC_INCR = {
	0x016090, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_VRES_MOTOR_REVS = {
	0x026090, IL_REG_DTYPE_U32, IL_REG_ACCESS_RW, IL_REG_PHY_NONE, NULL
};

const il_reg_t IL_REG_VEL_TGT = {
	0x0060FF, IL_REG_DTYPE_S32, IL_REG_ACCESS_RW, IL_REG_PHY_VEL, NULL
};
